name: playfabsdk
description: A PlayFabClient for Flutter.
version: 0.0.1
author: Arturo Gutiérrez
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0

flutter:
